/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: samuel.cseto@ysoft.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
    "net/http"

    "github.com/gin-gonic/gin"
)

type AmbulancesApi interface {

    // internal registration of api routes
    addRoutes(routerGroup *gin.RouterGroup)

    // CreateAmbulance - Saves new ambulance definition
    CreateAmbulance(ctx *gin.Context)

    // DeleteAmbulance - Deletes specific ambulance
    DeleteAmbulance(ctx *gin.Context)

}

// partial implementation of AmbulancesApi - all functions must be implemented in add on files
type implAmbulancesApi struct {

}

func newAmbulancesApi() AmbulancesApi {
    return &implAmbulancesApi{}
}

func (this *implAmbulancesApi) addRoutes(routerGroup *gin.RouterGroup) {
    routerGroup.Handle( http.MethodPost, "/ambulance", this.CreateAmbulance)
    routerGroup.Handle( http.MethodDelete, "/ambulance/:ambulanceId", this.DeleteAmbulance)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateAmbulance - Saves new ambulance definition
// func (this *implAmbulancesApi) CreateAmbulance(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteAmbulance - Deletes specific ambulance
// func (this *implAmbulancesApi) DeleteAmbulance(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
