/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: samuel.cseto@ysoft.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
    "net/http"

    "github.com/gin-gonic/gin"
)

type AmbulanceConditionsApi interface {

    // internal registration of api routes
    addRoutes(routerGroup *gin.RouterGroup)

    // GetConditions - Provides the list of conditions associated with ambulance
    GetConditions(ctx *gin.Context)

}

// partial implementation of AmbulanceConditionsApi - all functions must be implemented in add on files
type implAmbulanceConditionsApi struct {

}

func newAmbulanceConditionsApi() AmbulanceConditionsApi {
    return &implAmbulanceConditionsApi{}
}

func (this *implAmbulanceConditionsApi) addRoutes(routerGroup *gin.RouterGroup) {
    routerGroup.Handle( http.MethodGet, "/waiting-list/:ambulanceId/condition", this.GetConditions)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetConditions - Provides the list of conditions associated with ambulance
// func (this *implAmbulanceConditionsApi) GetConditions(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
